[toolchain]
anchor_version = "1.1.2"

[features]
seeds = true
skip-lint = false

[programs.localnet]
eutxo_amm = "6cmEegP2W9pBaP2CB7ZkyupZxM8NZUwU3NiqSE7ci5iR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
